name: DreamLand
main: me.cmesh.DreamLand.DreamLandPlugin
version: 5.0
softdepend: [SmoothFlight]
commands:
   wakeup:
      description: User will leave the dream they are in
      usage: |
          /wakeup
   setdreamspawn:
      description: User will set the world's spawn location
      usage: |
          /setdreamspawn